name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Windows
        run: |
          sudo apt-get update
          sudo apt-get install mingw-w64
          git clone https://github.com/libusb/libusb
          bash -c "cd libusb; ./autogen.sh --host=x86_64-w64-mingw32 --libdir=$PWD; make -j8 install-exec"
          make CC=x86_64-w64-mingw32-gcc CFLAGS="-static -s"
          zip -r snander.zip driver snander.exe

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: snander.zip
